apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: chat-app
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    name: frontend-pod
    namespace: chat-app
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: elcapitansid/chatapp-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"

