kind: PersistentVolumeClaim 
apiVersion: v1
metadata:
  name: mongodb-pvc
  namespace: chat-app
spec:
  resources:
    requests:
      storage: 1Gi #storage as per availability 
  accessModes:
    - ReadWriteOnce
