kind: ReplicaSet    # keeps desired replica pods count consistently.
apiVersion: apps/v1
metadata:
  name: replica
  namespace: nginx
  labels:
    app: nginx

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: pod 
      labels: 
        app: nginx

    spec:
      containers: 
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
